version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api/auth.db:/app/auth.db
    environment:
      - PRODUCT_SERVICE_ADDR=product:50052
      - WAREHOUSE_SERVICE_ADDR=warehouse:50053
      - SHOP_SERVICE_ADDR=shop:50054
    restart: unless-stopped

  order:
    build:
      context: .
      dockerfile: ./order/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./order/order.db:/app/order.db
    environment:
      - PRODUCT_SERVICE_ADDR=product:50052
      - WAREHOUSE_SERVICE_ADDR=warehouse:50053
    restart: unless-stopped

  product:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ./product/product.db:/app/product.db
    restart: unless-stopped

  warehouse:
    build:
      context: .
      dockerfile: ./warehouse/Dockerfile
    ports:
      - "50053:50053"
    volumes:
      - ./warehouse/warehouse.db:/app/warehouse.db
    restart: unless-stopped

  shop:
    build:
      context: .
      dockerfile: ./shop/Dockerfile
    ports:
      - "50054:50054"
    volumes:
      - ./shop/shop.db:/app/shop.db
    restart: unless-stopped
